using System.Collections.Generic;

namespace COLID.ResourceRelationshipManager.Common.DataModels.NewTOs
{
    public class MapNodeTO
    {
        public string Id { get; set; } //PID URI - the ONLY identifier for nodes!
        public string ShortName { get; set; } //Generated by the backend
        public string Name { get; set; }
        public KeyValuePair<string, string> ResourceType { get; set; }
        public IList<MapLinkTO> Links { get; set; }
        public double Fx { get; set; }
        public double Fy { get; set; }
    }
}
